[theme]
base="light"
primaryColor="#FFFFFF"  # White for the primary interface elements
backgroundColor="#FFFFFF"  # White for the main background
secondaryBackgroundColor="#87CEEB"  # Light blue for the sidebar
textColor="#000000"  # Black text for readability on the light background
font="sans serif"  # Keeping the sans serif font for a modern look
